---
- name: Create app directory
  file:
    path: /home/ubuntu/app
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'



- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes


- name: Clone microservices repo
  git:
    repo: "https://github.com/mastergid556/Node-Express-Microservices.git"
    dest: /home/ubuntu/app
    version: main

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /home/ubuntu/app/docker-compose.yml
    owner: ubuntu
    group: ubuntu
    mode: '0644'



- name: Create user-service .env file
  template:
    src: user-service.env.j2
    dest: /home/ubuntu/app/user-service/.env

- name: Create phone-service .env file
  template:
    src: phone-service.env.j2
    dest: /home/ubuntu/app/phone-service/.env

- name: Create api-gateway .env file
  template:
    src: api-gateway.env.j2
    dest: /home/ubuntu/app/api-gateway/.env

